{
  "formatVersion": "1.1",
  "component": {
    "group": "卷王",
    "module": "module-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-plugin-1.3.0.jar",
          "url": "lifecycle-plugin-1.3.0.jar",
          "size": 14604,
          "sha512": "01f17c1b69f307a7e8e1fb02508df07ff2240ee1ae50087783b5c49f515947e0908acf688d5efd6dc4ba585cff93b8918a3ece57966bce336886ecaa0b263952",
          "sha256": "08425eed7526cdcd0e578f0440eb49429a931c2d2c5ccd8ea9b7691f056d9359",
          "sha1": "89028676b0ca5d236d1c7bdd8f385d6e098fd562",
          "md5": "cf412f63e6303728c7d1a0822407c25f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.example.study",
          "module": "base-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-plugin-1.3.0.jar",
          "url": "lifecycle-plugin-1.3.0.jar",
          "size": 14604,
          "sha512": "01f17c1b69f307a7e8e1fb02508df07ff2240ee1ae50087783b5c49f515947e0908acf688d5efd6dc4ba585cff93b8918a3ece57966bce336886ecaa0b263952",
          "sha256": "08425eed7526cdcd0e578f0440eb49429a931c2d2c5ccd8ea9b7691f056d9359",
          "sha1": "89028676b0ca5d236d1c7bdd8f385d6e098fd562",
          "md5": "cf412f63e6303728c7d1a0822407c25f"
        }
      ]
    }
  ]
}
