{
  "formatVersion": "1.1",
  "component": {
    "group": "卷王",
    "module": "module-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-plugin-1.3.0.jar",
          "url": "lifecycle-plugin-1.3.0.jar",
          "size": 14831,
          "sha512": "a5ef0fd635a738b01e782998124848f1937cc694dd720b8a51d91ea623239b78d7d7af600d8551705faa1c81df9a16ddf9c2b779ac0a58182eed5643a19bb6ca",
          "sha256": "417426468526d0f0cc353ec2f2667dfc5e77bfca89aad2ec018d828fe373cd03",
          "sha1": "c57a43ca8794fdb6ad24c55f39e3fa51e29f57a5",
          "md5": "150a4456e1f9a7e6902a302bfb447a33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.example.study",
          "module": "base-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-plugin-1.3.0.jar",
          "url": "lifecycle-plugin-1.3.0.jar",
          "size": 14831,
          "sha512": "a5ef0fd635a738b01e782998124848f1937cc694dd720b8a51d91ea623239b78d7d7af600d8551705faa1c81df9a16ddf9c2b779ac0a58182eed5643a19bb6ca",
          "sha256": "417426468526d0f0cc353ec2f2667dfc5e77bfca89aad2ec018d828fe373cd03",
          "sha1": "c57a43ca8794fdb6ad24c55f39e3fa51e29f57a5",
          "md5": "150a4456e1f9a7e6902a302bfb447a33"
        }
      ]
    }
  ]
}
