{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.study",
    "module": "base-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "base-plugin-1.0.0.jar",
          "url": "base-plugin-1.0.0.jar",
          "size": 33976,
          "sha512": "38868a791d1553381e3634fe0eedc4e6c7fcb292a68482cf5806503852f09d1806e692c3ba6403a3b4c5d1c2e63a1c7426da24a57174491d7835359a764e22a5",
          "sha256": "9076aab07abac649b17bf9a7d498848e4c692e323000332c1d6d8bfdd99baaf7",
          "sha1": "525cc6d6357195f603773f1a3efe98dc6c0cb61c",
          "md5": "2a1e9bdad086d36642b117e6ded0e468"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "base-plugin-1.0.0.jar",
          "url": "base-plugin-1.0.0.jar",
          "size": 33976,
          "sha512": "38868a791d1553381e3634fe0eedc4e6c7fcb292a68482cf5806503852f09d1806e692c3ba6403a3b4c5d1c2e63a1c7426da24a57174491d7835359a764e22a5",
          "sha256": "9076aab07abac649b17bf9a7d498848e4c692e323000332c1d6d8bfdd99baaf7",
          "sha1": "525cc6d6357195f603773f1a3efe98dc6c0cb61c",
          "md5": "2a1e9bdad086d36642b117e6ded0e468"
        }
      ]
    }
  ]
}
