{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.study",
    "module": "base-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "base-plugin-1.0.0.jar",
          "url": "base-plugin-1.0.0.jar",
          "size": 33982,
          "sha512": "76ec5b0ceb795f948ea9abdcc6bf844fc1d5a7938ce579db5d2d720f6f9d44d23c04a0394c0f7bfc6e9b7cdd0b0090ebdc0525324fdbc986f1a36bb3e5759004",
          "sha256": "25555f67de98eb097f58b24817a011790671005a1f9db2bbc0580b2a99ed8824",
          "sha1": "6200b2d7061a0fd2ab3aaf2b2cec5378a04537af",
          "md5": "fb16e0883dfb518cb8a47cb766818a51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "base-plugin-1.0.0.jar",
          "url": "base-plugin-1.0.0.jar",
          "size": 33982,
          "sha512": "76ec5b0ceb795f948ea9abdcc6bf844fc1d5a7938ce579db5d2d720f6f9d44d23c04a0394c0f7bfc6e9b7cdd0b0090ebdc0525324fdbc986f1a36bb3e5759004",
          "sha256": "25555f67de98eb097f58b24817a011790671005a1f9db2bbc0580b2a99ed8824",
          "sha1": "6200b2d7061a0fd2ab3aaf2b2cec5378a04537af",
          "md5": "fb16e0883dfb518cb8a47cb766818a51"
        }
      ]
    }
  ]
}
