{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.study",
    "module": "base-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "base-plugin-1.0.0.jar",
          "url": "base-plugin-1.0.0.jar",
          "size": 33982,
          "sha512": "fcb6f06dce7549f2686ae03e9dac8256720fe8b504df54936960156ca211fc5095dde382e11027144570597f6d218b97c21b4a8858ed2caf8825721d51d1c045",
          "sha256": "b671d3fb24b61f706bc28620ca3b0d36cc811c944c18db2c65caac08f92bfc1a",
          "sha1": "99fa9182f293058b6aba46a9b09ea21b9e710958",
          "md5": "d67904e05137c65622a3d9039f94aa5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "base-plugin-1.0.0.jar",
          "url": "base-plugin-1.0.0.jar",
          "size": 33982,
          "sha512": "fcb6f06dce7549f2686ae03e9dac8256720fe8b504df54936960156ca211fc5095dde382e11027144570597f6d218b97c21b4a8858ed2caf8825721d51d1c045",
          "sha256": "b671d3fb24b61f706bc28620ca3b0d36cc811c944c18db2c65caac08f92bfc1a",
          "sha1": "99fa9182f293058b6aba46a9b09ea21b9e710958",
          "md5": "d67904e05137c65622a3d9039f94aa5a"
        }
      ]
    }
  ]
}
