{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.study",
    "module": "auto-register-plugin",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-register-plugin-1.0.3.jar",
          "url": "auto-register-plugin-1.0.3.jar",
          "size": 48097,
          "sha512": "ceedc0df333f6079540df64a42887166794ca230c5f66e74802a8688adfc64b45d0aba5d313095848d970932fdf638c86c7125482362c3d1caa529def708b885",
          "sha256": "1e73eab8b0d35253603f8905a830cdb9ca47fce3c291c4ee38a3423496b1b20b",
          "sha1": "221e5a11185e75b1734cdf8bcecb8a46bf3223c2",
          "md5": "b9d3b0898930bd6c9a17246b3b9f29c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "auto-register-plugin-1.0.3.jar",
          "url": "auto-register-plugin-1.0.3.jar",
          "size": 48097,
          "sha512": "ceedc0df333f6079540df64a42887166794ca230c5f66e74802a8688adfc64b45d0aba5d313095848d970932fdf638c86c7125482362c3d1caa529def708b885",
          "sha256": "1e73eab8b0d35253603f8905a830cdb9ca47fce3c291c4ee38a3423496b1b20b",
          "sha1": "221e5a11185e75b1734cdf8bcecb8a46bf3223c2",
          "md5": "b9d3b0898930bd6c9a17246b3b9f29c5"
        }
      ]
    }
  ]
}
