{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.study",
    "module": "auto-register-plugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "auto-register-plugin-1.0.1.jar",
          "url": "auto-register-plugin-1.0.1.jar",
          "size": 67326,
          "sha512": "1dd0f8176a1711f1996ed0c9e535206af6a0dcdc098722085adde1f53e384ca642ee03e03f346269f3e9da7d97113907cb9fca729c2b103564a6e94d03910c3c",
          "sha256": "dd9de703454ac4eb65564a1ffd59bcf5921110ae3c89bf070c0e4e685cc3d310",
          "sha1": "e6d9810e7d8a48a004fc7fd8187fa960b15c0385",
          "md5": "75242c847cc814088432a91f29581d46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "Study",
          "module": "interfaces",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "auto-register-plugin-1.0.1.jar",
          "url": "auto-register-plugin-1.0.1.jar",
          "size": 67326,
          "sha512": "1dd0f8176a1711f1996ed0c9e535206af6a0dcdc098722085adde1f53e384ca642ee03e03f346269f3e9da7d97113907cb9fca729c2b103564a6e94d03910c3c",
          "sha256": "dd9de703454ac4eb65564a1ffd59bcf5921110ae3c89bf070c0e4e685cc3d310",
          "sha1": "e6d9810e7d8a48a004fc7fd8187fa960b15c0385",
          "md5": "75242c847cc814088432a91f29581d46"
        }
      ]
    }
  ]
}
