{
  "formatVersion": "1.1",
  "component": {
    "group": "Study",
    "module": "module-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "module-plugin-unspecified.jar",
          "url": "module-plugin-unspecified.jar",
          "size": 14471,
          "sha512": "4f9dbbec546981fa76463c14edcb7a9868f4326d7e1e503e09d1b87019ca4ffa6b4ea6748757e89107efbb1cfe70ad9e66d4f38d13b90bb97ce4acd83eed33a0",
          "sha256": "b3233959427170eee5d1c53e873dd0cfe0400cc29b9128f5e410fef2db8fbb50",
          "sha1": "8e9edff7dae7673f84e973bc0ef46187b62b863c",
          "md5": "bc4fefdba2011ac007515c00b301d656"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.example.study",
          "module": "base-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "module-plugin-unspecified.jar",
          "url": "module-plugin-unspecified.jar",
          "size": 14471,
          "sha512": "4f9dbbec546981fa76463c14edcb7a9868f4326d7e1e503e09d1b87019ca4ffa6b4ea6748757e89107efbb1cfe70ad9e66d4f38d13b90bb97ce4acd83eed33a0",
          "sha256": "b3233959427170eee5d1c53e873dd0cfe0400cc29b9128f5e410fef2db8fbb50",
          "sha1": "8e9edff7dae7673f84e973bc0ef46187b62b863c",
          "md5": "bc4fefdba2011ac007515c00b301d656"
        }
      ]
    }
  ]
}
